#!/bin/sh
# Assembles vzboot.mac in both layouts and writes them as C arrays to
# firmware/esp32c3/main/bootcode.h. Needs Nestor80: N80=/path/to/N80 sh gen.sh
set -e
cd "$(dirname "$0")"
: "${N80:=N80}"
"$N80" vzboot.mac dos1.bin --build-type abs --no-show-banner
"$N80" vzboot.mac dos2.bin --build-type abs --no-show-banner --define-symbols DOS2
python3 - <<'PY'
def arr(name, path):
    b = open(path, 'rb').read()
    rows = [', '.join('0x%02X' % x for x in b[i:i+16]) for i in range(0, len(b), 16)]
    return 'static const uint8_t %s[%d] = {   // offset 0x1E of sector 0\n    %s\n};\n' % (name, len(b), ',\n    '.join(rows))
out = '// Generated by tools/bootsec/gen.sh from vzboot.mac - do not edit.\n#pragma once\n#include <stdint.h>\n' + arr('bootcode_dos1', 'dos1.bin') + arr('bootcode_dos2', 'dos2.bin')
open('../../firmware/esp32c3/main/bootcode.h', 'w').write(out)
print('dos1 %d bytes, dos2 %d bytes' % (len(open('dos1.bin','rb').read()), len(open('dos2.bin','rb').read())))
PY
rm -f dos1.bin dos2.bin
